sonar.projectKey=EPIC-Team-Beta_iDaVIE
sonar.organization=epic-team-beta

# Source encoding
sonar.sourceEncoding=UTF-8

# Global exclusions for non-code artifacts
sonar.exclusions=**/*.meta,**/Library/**,**/Temp/**,**/Obj/**,**/Build/**,**/Logs/**
