sonar.projectKey=EPIC-Team-Beta_iDaVIE
sonar.organization=epic-team-beta

sonar.sources=Assets/Scripts/PluginInterface,Assets/Scripts/VolumeData/VolumeDataSet.cs,Assets/Scripts/VolumeData/VolumeDataSetRenderer.cs,Assets/Scripts/Tools/Delegates.cs,Assets/Scripts/Tools/BenchmarkManager.cs,Assets/Scripts/VolumeData/Config.cs,.github/workflows

sonar.inclusions=**/*.cs,**/*.yml,**/*.yaml

sonar.exclusions=**/*.meta,**/Library/**,**/Temp/**,**/Obj/**,**/Build/**,**/Logs/**

sonar.sourceEncoding=UTF-8
