sonar.projectKey=EPIC-Team-Beta_iDaVIE
sonar.organization=epic-team-beta

# Optional display name/version in SonarCloud.
#sonar.projectName=iDaVIE
#sonar.projectVersion=1.0

# Choose what SonarCloud scans.
# Paths are relative to this sonar-project.properties file.
# Use "/" even on Windows.
#
# Scan the whole repo:
#sonar.sources=.
#
# Scan specific folders:
sonar.sources=Assets/Scripts
#
# Scan multiple folders/files:
#sonar.sources=Assets/Scripts,native_plugins_cmake,README.md

# Optional: include only certain file types inside sonar.sources.
#sonar.inclusions=**/*.cs,**/*.cpp,**/*.h,**/*.hpp

# Optional: exclude generated/build/cache files.
sonar.exclusions=**/*.meta,**/Library/**,**/Temp/**,**/Obj/**,**/Build/**,**/Logs/**

# Source encoding.
sonar.sourceEncoding=UTF-8
